### ISSUE TITLE
i got blank pages

### ISSUE THREAD

**Issue by Mrkebubun** [jclement/bitmessage-web#2]
i run the server in http://127.0.0.1:3000/
but the page still blank,
GET /lib/bootstrap/dist/css/bootstrap.min.css 404 17ms
GET /lib/angular-ui-select/dist/select.min.css 404 21ms
GET /lib/angular/angular.min.js 404 7ms
GET /lib/angular-route/angular-route.min.js 404 8ms
GET /lib/angular-sanitize/angular-sanitize.min.js 404 9ms
GET /lib/jquery/dist/jquery.min.js 404 11ms
GET /lib/bootstrap/dist/js/bootstrap.min.js 404 8ms
GET /lib/angular-ui-select/dist/select.min.js 404 7ms
GET /lib/underscore/underscore.js 404 32ms
GET /lib/noty/js/noty/packaged/jquery.noty.packaged.min.js 404 5ms
GET /lib/angular-local-storage/dist/angular-local-storage.min.js 404 33ms
GET /lib/angular-route/angular-route.min.js 404 1ms
GET /lib/angular-sanitize/angular-sanitize.min.js 404 1ms
GET /lib/jquery/dist/jquery.min.js 404 2ms
GET /lib/bootstrap/dist/js/bootstrap.min.js 404 1ms
GET /lib/angular-ui-select/dist/select.min.js 404 1ms
GET /lib/underscore/underscore.js 404 2ms
GET /lib/noty/js/noty/packaged/jquery.noty.packaged.min.js 404 1ms
GET /lib/angular-local-storage/dist/angular-local-storage.min.js 404 11ms

**Comment by jclement** [comment]
Did you install all the dependencies by running "bower install"?

**Comment by Mrkebubun** [comment]
\bitmessage-web-master\node_modu
les\bitmessage-node\lib\main.js:25
            if (error) throw error;
                             ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1010:19)

yes i install everything,and it running now but i got that error messege when i try to use the menu and refresh the page.
